// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "provider": string;
      "apiPreset": string;
      "apiAddress": string;
      "apiKey": string;
      "modelName": string;
      "targetLang": string;
      "promptTemplate": string;
      "shortcut": string;
      "shortcutHintDismissCount": number;
      "closePopupAfterCopy": boolean;
    };
  }
}
